#!/bin/bash

set -o errexit

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Get latest"
yum -y update --skip-broken || true

echo "* Install zabbix-agent"
rpm -Uvh https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
yum -y update 2>/dev/null || true
yum -y install zabbix-agent 2>/dev/null || true
mkdir -p /etc/zabbix/zabbix_agentd.conf.d || true

echo "* Add bash extensions"
cat >> /etc/skel/.bashrc << EOF
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$ '
alias la="ls -al"
alias t="cd /var/log/ && tail -n 50 -f "
alias msg="/usr/bin/tail -n 50 -f /var/log/syslog"
EDITOR=nano
HISTSIZE=2000
HISTFILESIZE=25000
HISTTIMEFORMAT="[%d.%m.%Y %T] "
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8
EOF

echo "* Add nano extensions"
cat >> /etc/nanorc << EOF
include "/usr/share/nano/ruby.nanorc"
include "/usr/share/nano/sh.nanorc"
include "/usr/share/nano/nanorc.nanorc"
include "/usr/share/nano/html.nanorc"
include "/usr/share/nano/css.nanorc"
include "/usr/share/nano/javascript.nanorc"
EOF

echo "* Setup language env"
cp /etc/skel/.bashrc /root/.bashrc
source /root/.bashrc
#locale-gen en_US.utf8

echo "* setup bootstrap startscript"
touch /var/lib/bootstrap
systemctl daemon-reload
systemctl enable /etc/systemd/system/bootstrap.service

echo "* Cleaning up."
rm /var/lib/bootstrap 2>/dev/null || true
rm /root/.bash_history 2>/dev/null || true
history -c
